### ISSUE TITLE
Fee per event

### ISSUE THREAD

**Issue by Tulpenzwiebel** [rmbinder/Mitgliedsbeitrag#122]
Hi all,
is it also possible to add an option regarding the payment period that you have to pay for each event you attended? 
For our use case we would need the possibility for a "regular member role" which pays a monthly fee and therefor doesn't have to pay per event and a secont "guest member role" (but still a role within the system, just not a regular participant) which pays a different fee per event. Is something like that possible?
Best!

**Comment by rmbinder** [comment]
First a basic question: Do you work with Admidio's events module? Or do you create a separate role for each event (with contribution, contribution period, etc.)?

**Comment by Tulpenzwiebel** [comment]
I'm working with the event module. Creating the event there, giving the user the possibilty to register for participation.

**Comment by Tulpenzwiebel** [comment]
Just thinking about the 2nd possibility:
Would the use case be possible via a role for each event, especially regarding the different payment models (regular vs. event based)? We would still have the need to add both users (regular members and guest members) to the role as we do need things like participation lists etc.
So this would require something like _if memer of "guest member" AND "participating in event Z" then fee=y else fee=0_ because regular member have their monthly costs assigned to the "regular member" role

Just an additional thought: if this is possible, would it also be a possibility to have this role assigned if a user is registered as participator in an event in the event module? So kind of having the management of this role delegated to the event module. Seems to be quite simple to have two hooks there like "create role when event is created", "assign user to role if registering".

**Comment by rmbinder** [comment]
In Admidio, events are just "roles". All participants of an event are basically only members of a role. However, it is currently not possible to assign a contribution and a contribution period to an event.

This possibility would have to be created (and of course it must be tested extensively whether this assignment of a contribution to an event has any negative effects on Admidio. Since it is not intended to assign a contribution to an event).

I once assigned a contribution and a contribution period to an event via phpMyAdmin as a test. This event was recognized by the Membership Fee plugin as a contribution role and I was also able to perform calculations.

So the following would be possible: I extend the plugin with the ability to assign a contribution and a contribution period to an event.
The process is then as follows:
- A new event is created.
- Members register for this event
- In the membership fee plugin, this event is assigned a contribution and a contribution period.
- A recalculation is performed (for all participants of this event)
- The regular members are marked as if they had paid via contribution payments.
- In Export - SEPA only the guest members are now listed. A SEPA XML file is only created for these guest members.

**Comment by rmbinder** [comment]
The fee per event feature is implemented in the feature-fee-per-event branch. Please test.
