### ISSUE TITLE
problems with SEPA-file format

### ISSUE THREAD

**Issue by baloo66** [rmbinder/Mitgliedsbeitrag#139]
We are having a problem uploading the SEPA file to our bank. The Sparkasse complains about the format: "The file format used is not supported. The supported file format for direct debits is PAIN 008.001.02...". A call to the hotline unfortunately has no result ("I don't have anything. It's usually because there is a newer program version for generation..."). 

Does anyone else have a problem like this? 

Is it possible that a “newer” version (possibly pain.008.001.02_GBIC_3.xsd version 3.3) is expected? So maybe sepa_export.php has to be changed or adapted?

**Comment by rmbinder** [comment]
Someone in the Admidio forum already had a problem sending the SEPA file to a Sparkasse. It is described [here:](https://www.admidio.de/forum/viewtopic.php?p=33340&hilit=pain+008&sid=08a0ea439b8a39691c6de1be0862efa7#p33340)

Membership fee creates SEPA files according to the PAIN 008.001.02 standard. The error must lie somewhere else.

In our sports club we had the problem about 2 weeks ago that the following error message came up when sending to a VR bank:
"SEPA-Sammellastschrift fehlerhaft. Auftrag abgelehnt. Zahlungsbeteiligter BIC ungültig."
After many hours (!!!!) I found out that a single (!!) IBAN was invalid. The IBAN was syntactically correct, but, probably due to a bank merger, the SWIFT/BIC code (the Bankleitzahl) no longer existed and the IBAN was therefore classified as incorrect.

Try dividing the SEPA file into smaller blocks: 50 direct debits, 10 direct debits, etc

**Comment by baloo66** [comment]
I contacted the Sparkasse concerned and the only information I got was "there's probably a new version of the program - just use that". So I gave up for the time being and wrote a simple script to convert the generated XML file into the format that worked last year. That worked and I got the job done. In this respect, the issue is currently no longer relevant to me. But I would like to stay on the topic so that we don't have the topic again next year...

**Comment by rmbinder** [comment]
You have converted the XML file into another format. What exactly did you change?

**Comment by baloo66** [comment]
We had the SEPA file from last year (created with another, quite old PC program), which was accepted by Sparkasse Rottal-Inn without any problems last year. After fumbling around for a while and running out of ideas (and our cashier getting impatient), I thought about gutting last year's SEPA file and reading in the XML file generated by admidio and outputting it in the structure of last year's file. I would be happy to "shrink" the new file (remove the real data) at the weekend and post it here. ATTENTION: I don't think that the file created by admidio is wrong, I rather think that the Sparkasse Rottal-Inn (or the FI-TS or the FI as the possibly executing IT unit) has inaccuracies.

**Comment by rmbinder** [comment]
👍

**Comment by baloo66** [comment]
ok - used to take longer than I intended ;-) ... attached two files: from_spk_not_accepted_created_by_membership_fee.xml is a file which was created by membership fee plugin (stripped down to one FRST and one RCUR transaction) - a file with that structure (and more transactions) was not accepted by the Sparkasse Rottal-Inn. And from_spk_accepted.xml which is the corresponding file (created by a mapping script) in the structure of 2023, which was accepted by Sparkasse Rottal-Inn.
AGAIN: I don't think that the file created by admidio is wrong, I rather think that the Sparkasse Rottal-Inn (or the FI-TS or the FI as the possibly executing IT unit) has inaccuracies.
