### ISSUE TITLE
No members visible in duedate-Module

### ISSUE THREAD

**Issue by piggeldi** [rmbinder/Mitgliedsbeitrag#93]
When storing the due date, no members can be selected, no matter how I define the filter setting. For mandates and payments, I see my members. I was also able to create a new mandate reference for all members. 

The following fields are filled in for the members: 

First name, Last name, IBAN, BIC, Bank, Mandate. 

![image](https://user-images.githubusercontent.com/6298379/149466386-b78b3fb4-f46f-48a2-9621-431b551412e2.png)

Furthermore, I do not see any errors in the Apache log. 

EDIT 1: I have also made sure that the contributions have been calculated and that all members have mandate references.
EDIT 2: Im using version  5.1.0

Many thanks for the help!

**Comment by rmbinder** [comment]
These specifications must be present so that members are displayed in the "Fälligkeitsdatum/Due date" module:

- Bezahlt / Paid: must be empty
- Beitrag / Fee: must not be empty
- IBAN: must not be empty
- Mandatsreferenz/Mandate reference (Mandate-ID): must not be empty
- Mandatsdatum/Mandate date: must not be empty

**Comment by piggeldi** [comment]
Mandatsdatum was missing. Thanks for your help again! 

Cheers!

**Comment by luebbe** [comment]
I remember having a difficult time getting up and running, because some of these prerequisites are not obvious. But if I remember correctly, they should all be covered by the consistency checks in the latest version. So if the checks don't show anything, you have a great chance that everything is set up correctly.
But I'm still a bit confused about the order in which things have to be defined. When I have to start again this year, I'll probably have to relearn everything again.

**Comment by rmbinder** [comment]
I am currently working on a sub plugin for my plugin tools. When I'm done, I'll start revising the documentation, including an English translation. After that things should be clearer.

**Comment by luebbe** [comment]
That sounds good. Would you also be so kind to check if the process of creating the membership fees can be streamlined a bit more? I'm still on Admidio 4.0, so I can't see how it is with the latest version. Have to check if the statistics plugin is also updated to 4.1 before I can take the leap.

I wrote a membership database using MS Access 95, while I was the cashier, so you can guess how old it is. This worked fine while everybody had a copy of MS Access on their PC. But since this is no longer the case, it was time to move on. 
Porting to Libre Office was one option, but first I evaluated what else exists and came across Admidio.

Now, slowly getting to the point: Since the cashiers following after me were not that computer literate, everything, especially the membership fees, had to be very easy. So I had one form to create the membership fees and one to check the balance.
The "create" form had number of buttons, which took the cashier through the process. I was like:
1. Run consistency checks
    - List errors (missing mandate date, incorrect IBAN etc.)
    - Enable/Disable buttons 2&3 depending on check result
2. Create SEPA files
3. Create PDF invoices

The "check" form was like admidio and allowed to set the date when the fee was paid.

Right now the "create" process in Admidio doesn't feel straightforward to me. It is a bit "here" and "there". Our current cashier is also a software developer, so the two of us can cope with it, but when I imagine our "president" trying to create the membership fees, I can only see failure.

I don't know how the plugin/UI concept of Admidio works, but right now in Membership fee, you have like four tabs with several options on each tab. When you look at it for the first time, it's a "Matrix of hidden functionality".

Don't get me wrong. It looks like everything is there and over all it's a lot better than my solution, but it's not easy to get started from scratch. After everything is set up, it's a lot smoother. If you don't have to touch the difficult one-time-bits again you don't see them.
